version: "3.9"

services:

  zenoh-router:
    image: eclipse/zenoh:0.7.2-rc
    restart: unless-stopped
    environment:
      - RUST_LOG=${ZENOH_LOG_LEVEL:-debug}
    command:
      [
        "--connect tls/zenoh.mo.ri.se:443",
        "--cfg mode:'router'",
        "--cfg plugins/storage_manager/storages/latest_local/volume:memory",
        "--cfg plugins/storage_manager/storages/latest_local/key_expr:keel/${LOCATION:-test}/**"
      ]
