version: "3.9"

services:

  # Reverse proxy
  traefik:
    image: "traefik:v2.10.4"
    restart: unless-stopped

    # Static configuration of Traefik
    environment:
      # General configuration
      - TRAEFIK_LOG_LEVEL=${TRAEFIK_LOG_LEVEL:-ERROR}
      - TRAEFIK_ACCESSLOG=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS=Label(`keel.expose`, `true`)

      # Entrypoints
      - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443

      # Catch-all redirection from http to https
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https

      # TLS certificate through Let's Encrypt
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver=true
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_EMAIL=${ACME_EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_HTTPCHALLENGE=true
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_HTTPCHALLENGE_ENTRYPOINT=web
      - TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_STORAGE=/letsencrypt/acme.json
      #- TRAEFIK_CERTIFICATESRESOLVERS_leresolver_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory

    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - vol-traefik-letsencrypt:/letsencrypt

  zenoh-router:
    image: eclipse/zenoh:0.7.2-rc
    restart: unless-stopped
    labels:
      - "keel.enable=true"
      - "traefik.tcp.routers.zenoh.rule=HostSNI(`${HOSTNAME}`)"
      - "traefik.tcp.routers.zenoh.tls.certresolver=LEresolver"
      - "traefik.tcp.routers.zenoh.service=zenoh-service"
      - "traefik.tcp.services.zenoh-service.loadbalancer.server.port=7447"
    environment:
      - RUST_LOG=${ZENOH_LOG_LEVEL:-debug}
    command:
      [
        "--listen tcp/[::]:7447",
        "--no-multicast-scouting",
        "--cfg mode:'router'"
      ] #"--cfg transport/auth/usrpwd/dictionary_file:'/credentials.txt'"
    # volumes:
    #   - ./credentials.txt:/credentials.txt

volumes:
  vol-traefik-letsencrypt:
