version: '3.9'

services:
  zenoh-router:
    image: eclipse/zenoh:0.10.0-rc
    restart: always
    network_mode: host
    environment:
      - RUST_LOG=${ZENOH_LOG_LEVEL:-debug}
    command:
      [
        "--listen tcp/[::]:7447",
        "--cfg=mode:'router'",
        "--cfg=plugins/storage_manager/storages/latest_local/volume:'memory'",
        "--cfg=plugins/storage_manager/storages/latest_local/key_expr:'${REALM}/${LOCATION}/**'"
      ]
