name: 'Testing'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            black --check --verbose interfaces/*/bin/*[!.odvd]
            black --check --verbose sdks/python --extend-exclude _pb2.py

            pytest -vv sdks/python/tests
            
      - name: Check Proto File Syntax
        run: |
          find . -name "*.proto" -exec protoc --proto_path=. --include_imports --include_source_info --descriptor_set_out=/dev/null {} \;
